### PR TITLE
Migrate to homebrew-core

### LINKED ISSUE #97: Graduate to central homebrew repository
Since you have almost 9k stars, you are eligible to submit your formula to https://github.com/Homebrew/homebrew-core/blob/master/Formula/ instead of maintaining your own tap.

### PR DESCRIPTION
**Pull request by chenrui333**
Closes https://github.com/wagoodman/dive/issues/97

Homebrew PR, https://github.com/Homebrew/homebrew-core/pull/42492
README update PR, https://github.com/wagoodman/dive/pull/213

### CODE REVIEW

**Comment by chenrui333** [comment]
@wagoodman  We might still need this to redirect the traffic to homebrew-core :)

**Comment by chenrui333** [comment]
@wagoodman ping :)

**Comment by wagoodman** [comment]
thanks for your patience @chenrui333 , this may have slid off my radar :flushed:

**Comment by chenrui333** [comment]
No worries, thanks for the merge.

**Pull request merged**
